server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: transaction-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/transactions/**
        - id: merchant-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/merchants/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
