CREATE TABLE IF NOT EXISTS public.transactions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(38,2),
    card_number_masked VARCHAR(255),
    card_type VARCHAR(255),
    channel VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    currency VARCHAR(255),
    device_id VARCHAR(255),
    flag_reason VARCHAR(255),
    ip_address VARCHAR(255),
    is_flagged BOOLEAN,
    location VARCHAR(255),
    merchant_id VARCHAR(255),
    response_code VARCHAR(255),
    review_status VARCHAR(255),
    risk_score INTEGER,
    transaction_id VARCHAR(255) NOT NULL UNIQUE,
    transaction_time TIMESTAMP(6) WITHOUT TIME ZONE,
    transaction_type VARCHAR(255),
    flagged_at TIMESTAMP(6) WITHOUT TIME ZONE,
    flagged_by VARCHAR(255),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.transactions OWNER TO fraud_user;
