CREATE TABLE IF NOT EXISTS public.merchants
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acquirer_name VARCHAR(255),
    category VARCHAR(255),
    city VARCHAR(255),
    country VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    domain VARCHAR(255),
    is_high_risk BOOLEAN,
    merchant_id VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

ALTER TABLE public.transactions
ADD CONSTRAINT fk_transactions_merchant
FOREIGN KEY (merchant_id)
REFERENCES public.merchants (merchant_id)
ON UPDATE CASCADE
ON DELETE RESTRICT;

ALTER TABLE public.merchants OWNER TO fraud_user;

